import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'
import { fileURLToPath, URL } from 'node:url'
import vuetify, { transformAssetUrls } from 'vite-plugin-vuetify'

// Vite plugin to transform <i18n lang="yaml"> SFC blocks into JS modules.
// @vitejs/plugin-vue returns custom blocks (including i18n) as raw content
// without a transform step. We convert YAML/JSON to a default-exported object
// so the bundler can resolve the import generated by genCustomBlockCode.
function vueI18nCustomBlock () {
  return {
    name: 'vue-i18n-custom-block',
    enforce: 'pre',
    transform (code, id) {
      if (!id.includes('?vue&type=i18n')) return null
      const langMatch = id.match(/[?&]lang\.([^&]+)/)
      const lang = langMatch ? langMatch[1] : null
      let parsed
      if (lang === 'yaml' || lang === 'yml') {
        parsed = parseSimpleYaml(code)
      } else {
        try { parsed = JSON.parse(code) } catch { parsed = code }
      }
      return {
        code: `export default ${JSON.stringify(parsed)}`,
        map: null
      }
    }
  }
}

// Minimal YAML parser for the 2-level shape used in DataFair apps
// (locale blocks mapping to flat key:value pairs).
function parseSimpleYaml (src) {
  const result = {}
  const lines = src.split(/\r?\n/)
  let currentLocale = null
  for (const raw of lines) {
    const line = raw.replace(/#.*$/, '').replace(/\s+$/, '')
    if (!line) continue
    const localeMatch = line.match(/^([A-Za-z_][\w-]*):\s*$/)
    if (localeMatch) {
      currentLocale = localeMatch[1]
      if (!result[currentLocale]) result[currentLocale] = {}
      continue
    }
    const kvMatch = line.match(/^\s+([^:]+):\s*(.*)$/)
    if (kvMatch && currentLocale) {
      const key = kvMatch[1].trim()
      let value = kvMatch[2].trim()
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1)
      }
      result[currentLocale][key] = value
    }
  }
  return result
}

export default defineConfig({
  base: process.env.PUBLIC_URL ?? '/app/',
  plugins: [
    vue({
      template: { transformAssetUrls }
    }),
    vueI18nCustomBlock(),
    vuetify({
      autoImport: true,
      styles: {
        configFile: 'src/styles/settings.scss'
      }
    })
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    },
    extensions: ['.js', '.json', '.mjs', '.ts', '.vue']
  },
  server: {
    port: 3000,
    hmr: {
      port: 3000,
      protocol: 'ws'
    }
  }
})
